.env.example, README.md, docker-compose.yml
Allow for wikibase (e.g. in the mediawiki development enviroment) to
reach the SSR service by making it available in a docker network
configurable in the .env file.
Works for example with https://github.com/addshore/mediawiki-docker-dev/
=> docker: make SSR service available in MW network

dist/wikibase.termbox.main.css, package.json
The CSS build previously got lost because the `NODE_ENV` variable was set to development during the build command. This should never happen so we might as well always set it to `production` within the command.
=> Check in CSS build

package.json
`--mode server` does not actually do anything for us. `--mode` can be used to load different environment configs, but we're not actually doing that. Reference: https://cli.vuejs.org/guide/mode-and-env.html#modes
=> Remove `--mode server` for the build-server npm command

jsduck.json
ES6 syntax is not supported[0] which is causing problems when building the
entire project and so far it is not clear what we want to go into the
documentation anyhow.
[0] https://github.com/senchalabs/jsduck/issues/630
Bug: https://phabricator.wikimedia.org/T208226
Try via 
```
docker run -it --rm -v $(pwd):/workdir tozny/jsduck jsduck
=> T208226 jsduck: add (disabling) configuration

tslint-wikimedia-eslint-rules-port.json
`"binary-expression-operand-order": true` prevents expressions like `false === foo` and the like.
`"variable-name": [true, "ban-keywords", "check-format"]` limits variable names to lowerCamelCase or UPPER_CASE and disallows keywords.
I didn't find a way to limit naming for method and class/interface property names. If someone finds something, please add that.
=> Add tslint rules for yoda expressions and variable names

README.md
We observed some versions of docker-compose (e.g. 1.19.1) to fail when
MEDIAWIKI_NETWORK_TO_JOIN was set to an empty string while others
(e.g. 1.17.1) created a custom, prefixed network instead. Added a
warning.
=> docker-compose: document need for correct .env

src/mockup-entry.ts, src/server-entry.ts, tsconfig.json
See https://www.typescriptlang.org/docs/handbook/compiler-options.html
This now run during the build steps instead of the lint step.
=> tsconfig: check for unused imports

.travis.yml, Dockerfile, README.md, docker-compose.yml
The node docker image comes with a 'node' user that can (and should) be
used instead of root. Setting its user id to the one of your user on the
host system ensures that files generated into the mounted volumes are
owned by you.
Make sure to give the README another read!
See https://github.com/nodejs/docker-node/blob/526c6e618300bdda0da4b3159df682cae83e14aa/8/jessie/Dockerfile#L3
Interestingly, even though we've been running npm through the container before, I now see changes to `package-lock.json` after running `npm install` (`"optional": true` stuff) - not sure yet, if we should check that in or not.
=> container node: ensure right user

src/common/interfaces/TermboxRequest.ts
Adds interface to be implemented by both client and server to describe
state to be committed to app store. Code thereafter should be identical.
I would not mind if we come up with a better folder name as soon as patterns emerge.
Bug: T209283
=> TermboxRequest: provide interface

jest.config.js, tests/config/setup.ts
Without this, the following would add a passing test to our suite.
it( 'potato', () => {
} );
=> Ensure every test has assertions

jest.config.js, package-lock.json, package.json, src/server/data-access/MwBotWikibaseRepo.ts, src/server/data-access/WikibaseRepo.ts, src/server/data-access/error/EntityNotFound.ts, src/server/data-access/error/TechnicalProblem.ts, src/types/server/mwbot.d.ts, tests/unit/server/data-access/MwBotWikibaseRepo.spec.ts, tsconfig.all.json, tsconfig.server.json
Done through mwbot.
This makes our tests (ts-jest) use the tsconfig.all.json until we get to
re-organize the test folder to be able to test client-only and server-only (and possibly mixed) individually.
This is to ensure the typeRoots defined (for server) are not made obsolete by being excluded thereafter.
Bug: T207467
=> WikibaseRepo: add way to get entity on server (api)

src/server/data-access/MwBotWikibaseRepo.ts, tests/unit/server/data-access/MwBotWikibaseRepo.spec.ts, tslint.json
Ensure that CI is able to pick up liniting violations until tslint matures
further: palantir/tslint#2604
This makes the output look slightly different but it contains the same
information.
Also cleans up some warnings that slipped through CI before.
=> linting: let CI fail if there are warnings

package-lock.json, package.json, src/server/route-handler/termbox/QueryValidator.ts, src/server/route-handler/termbox/TermboxHandler.ts, src/server/route-handler/termbox/error/EntityNotFound.ts, src/server/route-handler/termbox/error/InvalidRequest.ts, src/server/route-handler/termbox/error/TechnicalProblem.ts, tests/unit/server/route-handler/termbox/QueryValidator.spec.ts, tests/unit/server/route-handler/termbox/TermboxHandler.spec.ts
Ability to derive the TermboxRequest from the HTTP request (query)
Consider `QueryValidator` the MVP of what can be done to make sure only sane inputs reach the next layer.
Bug: T207467
=> TermboxHandler: dynamically create TermboxRequest

src/server/route-handler/termbox/error/EntityNotFound.ts, src/server/route-handler/termbox/error/InvalidRequest.ts, src/server/route-handler/termbox/error/TechnicalProblem.ts, tsconfig.server.json
Lack of features expected from the server side (https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work)
led us to discover that the target was actually set to ES5.
This obsoletes manual prototype setting.
=> custom errors: ensure correct prototype

src/server/data-access/WikibaseRepo.ts
Method documentation was placed on class level by accident.
=> WikibaseRepo: fix ill-placed doc

babel.config.js, jest.config.js, jsduck.json, postcss.config.js, tsconfig.all.json, tsconfig.json, tsconfig.server.json, tslint.json, vue.config.js
Let tslint check our JS (configuration) files in the project root, too.
With the release of palantir/tslint#3641 (I subscribed) the manual [prototypical] re-specification of `jsRules` will hopefully be obsolte soon.
Consistently indent JSON files. This goes against the tab indentation we
do for program files but allows for configuration files modified by
programs (e.g. npm using JSON.stringify() for package.json) to stay
consistent in the long run.
=> Configuration code style

jest.config.js
Warnings became annoying. Effective change is `tsConfigFile` to
`tsConfig`.
Warnings were
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].globals.ts-jest.tsConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
Did run
docker-compose run --rm node npx ts-jest config:migrate jest.config.js
=> migrate jest config to newer version

src/store/entity/exceptions/InvalidRawEntityException.ts
Remove unused file containing an exception class definition not matching
its file name.
=> InvalidRawEntityException: rm unused file

tests/unit/client/data-access/EntityRepository.spec.ts
Omit the confusing and unneeded use of mock-data/MwConfig, instead prove
that it is - despite being globally available - not accessed by
EntityRepository.
=> EntityRepository.spec: omit mock data use

src/server-entry.ts
A mwbot instance can perform more than one request. In addition it is
likely we will further configure this instance in the future (auth,
custom user agent, ...) so it is more convenient to do so.
=> server: reuse same mwbot for all repo access

package-lock.json, package.json, src/server/app.ts, tests/edge-to-edge/server/app.spec.ts
Use constants provided by
https://www.npmjs.com/package/http-status-codes instead of magic
strings.
=> server: use constants for HTTP status codes

src/components/App.vue
Avoid deprecated CSS import which caused a warning.
"Including .css files with @import is non-standard behaviour which
will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your
implementations documentation on how to create a custom importer."
=> reset-css: use sass import

.dockerignore, .pipeline/blubber.yaml, README.md
Add basic blubber configuration, with variants
* build - effectively `npm install`
* build-server - equivalent to npm's 'build-server' script
* test - equivalent to npm's 'test' script
Certain folders will not be copied into images - they are derived and
supposed to be created inside.
See
https://wikitech.wikimedia.org/wiki/Blubber#Use
https://wikitech.wikimedia.org/wiki/Streamlined_Service_Delivery_Design#Testing/building_pipeline
https://github.com/wikimedia/mathoid/blob/master/.pipeline/blubber.yaml
https://gerrit.wikimedia.org/r/#/c/wikidata/query/gui/+/472649/6/.pipeline/blubber.yaml
Added a `blubber` [bash alias](https://github.com/wiese/dot-files/blob/master/.bash_aliases) to my list for convenience.
Bug: T211321
=> blubber: build and test

tests/edge-to-edge/server/app.spec.ts
edge-to-edge tests are simulating actual requests against the server
and are - by definition - run in a development context. While the
production tip is valuable for the server (should we bork config) it
makes no sense to show it during tests.
=> tests: hide production tip in e2e tests

src/store/entity/index.ts, src/store/entity/mutationTypes.ts, src/store/language/index.ts, src/store/language/mutationTypes.ts, src/store/namespaces.ts, src/store/user/index.ts, src/store/user/mutationTypes.ts, tests/unit/store/data/UserStores.ts, tslint.json
Unfortunately, this only works for variables and parameters (but not return types?), and only for number, string, or boolean. https://palantir.github.io/tslint/rules/no-inferrable-types/
I stumbled across this looking for something that can help us prevent unnecessary casting, which I saw in quite some places, but as far as I can tell there is no such thing.
=> Disallow inferrable type declarations

package-lock.json, package.json
We run typescript with the configuration `importHelpers: true`,
consequently the compiler will inject helper functions into the
generated output that are called at run-time. These helper functions
reside in the tslib library which consequently has to be installed.
So far it has only been installed as a 3rd party dependency of some of
our dev dependencies. Consequently running the server with only prod
dependencies installed, as we plan for production, failed.
See
https://blog.mariusschulz.com/2016/12/16/typescript-2-1-external-helpers-library
https://www.npmjs.com/package/tslib
=> tslib: ensure presence in prod installation

src/client/data-access/UlsLanguageTranslationRepository.ts, src/mockup-entry.ts, src/server/data-access/ContentLanguagesLanguageRepo.ts, tests/unit/client/data-access/UlsLanguageRepository.spec.ts, tests/unit/components/TermBox.spec.ts, tests/unit/server/data-access/ContentLanguagesLanguageRepo.spec.ts, tests/unit/server/data-access/ContentLanguagesLanguageTranslationRepo.spec.ts, tests/unit/store/entity/getters.spec.ts, tests/unit/store/entity/mutations.spec.ts, tests/unit/store/language/actions.spec.ts, tests/unit/store/language/getters.spec.ts, tests/unit/store/language/mutations.spec.ts
Explicit type hints are fine and can be helpful even if they are technically redundant, but unnecessary casts are confusing, because they give the impression that we're forcing an object into a type that it isn't.
=> Remove unnecessary type casts

src/server/app.ts
When passed a file name, bundle renderer knows how to unpack the bundle.
Let it perform this action as it probably knows best - better than our
own code at least.
https://github.com/vuejs/vue/blob/52719ccab8fccffbdf497b96d3731dc86f04c1ce/src/server/bundle-renderer/create-bundle-renderer.js#L41
=> app: let bundle renderer unpack the bundle

tests/unit/client/init.spec.ts
Previously, the used method was not mocked which caused the test to
result in an unhandled promise - and as this was only a warning it
stayed green.
Goes into #132
Bug: T212409
=> tests: ensure init.spec mocks used getUrl method

tests/unit/client/init.spec.ts
Since there was another assertion in the test, and it did not actively
wait for the promise to be resolved, the test passed without evaluating
the second assertion.
=> Use conventional test syntax instead of magic "resolves"

tests/config/setup.ts, tests/unit/client/init.spec.ts
As opposed to just showing a warning that might get eaten in cli when
multple jest child processes work in parallel.
See https://github.com/facebook/jest/issues/3251
This is a bit unsatifactory as it makes the parent jest process hang in
case there are such occurances.
Should be green again with #133
Bug: T212409
=> tests: throw in case we encounter unhandled promise rejection

src/mock-data/MwConfig.ts, src/mock-data/getOrEnforceUrlParameter.ts, src/mockup-entry.ts
This makes it possible to try out the termbox in languages other than `de` by appending `?uselang=ar` for example.
=> Provide a way to test rtl languages in dev mode.

package-lock.json, package.json, src/mock-data/getOrEnforceUrlParameter.ts
Older browsers, i.e. IE10, may not natively support URLSearchParams
This is only relevant for the development preview.
Follow-up for #143
=> Show language used in dev mode in URL in older browsers

src/server/app.ts
Log - not otherwise explicitly handled - errors to console
(i.e. stdout) to be able to debug.
This also omits potential security problems that could arise from
sending stack traces to browsers during technical problems.
Could be worthwile to do this conditionally based on env, or even
implement some logger that facilitates a centralized logging
infrastructure for prod.
=> debugging: log server errors to console

src/server/app.ts, src/server/bundle-renderer/BundleRendererServices.ts, src/server/server.ts, tests/edge-to-edge/server/app.spec.ts, tests/unit/server/bundle-renderer/BundleRendererContext.spec.ts, tests/unit/server/bundle-renderer/BundleRendererContextBuilder.spec.ts, tests/unit/server/bundle-renderer/BundleRendererServices.spec.ts
Overcome two problems in e2e tests
* e5068d4
In 3 places, backend requests that are actually performed were not mocked
* 2d92121
Make the logger used by the server-side application configurable so it does not spill to stdout during e2e tests - could also be useful in production when hooking up something more elaborate (then we should probably assert how the logger communicates its findings to the outside rather than what it receives as input)
If anyone is worried about calling this e2e after the latter change let's quickly discuss how we solve this.
=> fix e2e test challenges

.travis.yml, package-lock.json, package.json
To form a central entry point for all our project's code quality tools.
This allows [blubber to execute linting](https://github.com/wmde/wikibase-termbox/blob/3433dc80c288fc59a12d645042f2c598d7d94bd3/.pipeline/blubber.yaml#L22).
The test (without "run") command is somewhat of a reserved word
in npm so our use should align with the eco system standards
(i.e. entry point for all the project's testing) even if it
means we have to relearn something.
https://docs.npmjs.com/cli/test.html
Added a [helper lib](https://www.npmjs.com/package/npm-run-all) to ease x-platform batch execution
Have bash completion as my excuse
https://corgibytes.com/blog/2017/04/18/npm-tips/#npm-completion
=> npm: run all CI via "test"

src/server/server.ts
To be able to stop the process through ctrl+c (SIGINT) when running
the server built for production (via `docker(-compose) run`).
Probably will be replaced by a more elaborate solution when looking
into graceful shutdown.
See
https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html
https://github.com/godaddy/terminus
Bug: T211675
=> server: react to SIGINT
