src/server/app.ts

path was not used but imported still

app.ts: remove unused import

---

package-lock.json

Check it in to allow for sane collaboration.
See https://docs.npmjs.com/files/package-lock.json#description

package-lock: check it in

---

.travis.yml

Avoid sending email if all is well.

travis: no email for successful build

---

.env.example
.travis.yml
README.md

* Ensure the dist folder matches the rest of the repo to avoid e.g. #20 
* run npm scripts in container we use in dev, too

travis: run in container & check dist/ build matches

---

src/server-entry.ts
src/server/app.ts

This allows us to perform asynchronous operations when preparing the app
(in the next step).
Bug: T207467

renderer: use promise to pass app

---

README.md
docs/typescript.md

We separated the tsconfig files. This provides a little context why and
what this individual files are responsible for.

doc: provide documentation for tsconfigs

---

src/server/app.ts

Variables that saw little use before had names that should be more
descriptive.

app.ts: use descriptive variable names

---

src/common/data-access/error/TranslationLanguageNotFound.ts
src/server-entry.ts
src/server/TermboxConfig.ts
src/server/data-access/WikibaseApiLanguageRepository.ts
src/server/server.ts
tests/edge-to-edge/server/app.spec.ts
tests/unit/server/data-access/WikibaseApiLanguageRepository.spec.ts

server: add ability to load language names

---

package-lock.json
package.json

Update to latest version to avoid vulnerability by 3rd party dependency.
https://www.npmjs.com/advisories/722

@vue/cli-plugin-unit-jest: update

---

.gitreview

For the upcoming gerrit/git review experience

Added .gitreview file

---

src/server-entry.ts
src/server/data-access/MwBotWikibaseFingerprintableEntityRepo.ts
tests/unit/server/data-access/MwBotWikibaseFingerprintableEntityRepo.spec.ts

Somehow the class name did not really say what it was doing. Now its
clumsy but less vague.

MwBotWikibaseFingerprintableEntityRepo: naming

---

src/server/app.ts

To ease use, more self-explanatory code.

app.ts: hint type for server app

---

package-lock.json
package.json

Update to latests @vue/test-utils.
This fixes, amongst others,
https://github.com/vuejs/vue-test-utils/issues/973 encountered during #137

tests: update @vue/test-utils

---

src/mock-data/MwConfig.ts
src/mock-data/getOrEnforceUrlParameter.ts
src/mockup-entry.ts

So that it's clear which language we look at and can easily change it.

Show language used in dev mode in URL

---

docs/browserslist.md

Document browserlist

---

docs/i18n.md

messages: document use

---

docs/diff-client-server.md

Try and document some of the known quirks.

doc: differences between client and server code

---

README.md

Follow-up for https://github.com/wmde/wikibase-termbox/pull/167

npm: document script changes

---

.pipeline/blubber.yaml
README.md

blubber: add prod variant

---

tests/unit/components/Fingerprint.spec.ts

Fingerprint.spec: refactor to ease adding to it
